### ISSUE TITLE
invert logo colors in dark mode

### ISSUE THREAD

**Issue by hyyan** [webforj/webforj-docs#149]
```css
[data-theme="dark"] .navbar__logo img {
  filter: brightness(0) invert(1);
}
```
